# Generated by Django 3.1.1 on 2020-09-13 11:05

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(
                blank=True,
                max_length=2,
                null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='county',
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='street_address1',
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='street_address2',
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(
                blank=True,
                default='',
                max_length=254,
                null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='town_or_city',
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True),
        ),
    ]
