# Generated by Django 3.1 on 2020-09-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('header_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('developer', models.CharField(blank=True, max_length=254, null=True)),
                ('publisher', models.CharField(blank=True, max_length=254, null=True)),
                ('platforms', models.CharField(blank=True, max_length=254, null=True)),
                ('required_age', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('positive_ratings', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('negative_ratings', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categories', models.ManyToManyField(to='games.Category')),
                ('genres', models.ManyToManyField(to='games.Genre')),
                ('tags', models.ManyToManyField(to='games.Tags')),
            ],
        ),
    ]
