# Generated by Django 3.1 on 2020-09-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='negative_ratings',
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='positive_ratings',
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='required_age',
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
