# Generated by Django 3.1 on 2020-09-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200905_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
