# Generated by Django 3.1 on 2020-09-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200905_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(blank=True, to='games.Category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, to='games.Genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, to='games.Tag'),
        ),
    ]
