# Generated by Django 3.1 on 2020-09-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20200905_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='game',
            name='discount',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=6),
        ),
        migrations.AddField(
            model_name='game',
            name='discounted',
            field=models.BooleanField(default=False),
        ),
    ]
