# Generated by Django 3.1 on 2020-09-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20200907_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='discount',
            new_name='discount_percent',
        ),
    ]
