# Generated by Django 3.1.1 on 2020-09-19 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20200919_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
