# Generated by Django 3.1.1 on 2020-09-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20200919_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='positive_ratings',
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=10,
                null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='required_age',
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=10,
                null=True),
        ),
    ]
