# Generated by Django 3.1.1 on 2020-09-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20200920_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='negative_ratings',
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=10,
                null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6),
        ),
    ]
