# Generated by Django 3.1.1 on 2020-09-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20200920_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='required_age',
        ),
    ]
