# Generated by Django 3.1.1 on 2020-09-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20200921_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discounted_price',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=6),
        ),
    ]
