# Generated by Django 3.1.1 on 2020-09-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_game_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=6, null=True),
        ),
    ]
