# Generated by Django 3.1.1 on 2020-09-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20200924_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discounted_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=6,
                null=True),
        ),
    ]
