# Generated by Django 3.1.1 on 2020-09-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20200924_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='discounted_price',
        ),
    ]
