# Generated by Django 3.1.1 on 2020-09-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_remove_game_price_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price_calculated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
