# Generated by Django 3.1.1 on 2020-09-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_game_price_calculated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price_calculated',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=6,
                null=True),
        ),
    ]
