# Generated by Django 3.1.1 on 2020-09-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_auto_20200924_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='price_calculated_value',
        ),
    ]
